
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async isDev() : Promise<boolean> {
    return await TAURI_INVOKE("is_dev");
},
async discoverWled(durationSecs: number | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_wled", { durationSecs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startEffect(virtualId: string, config: EffectConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_effect", { virtualId, config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stopEffect(virtualId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_effect", { virtualId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateEffectSettings(virtualId: string, settings: EffectConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_effect_settings", { virtualId, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addVirtual(config: Virtual) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_virtual", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateVirtual(config: Virtual) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_virtual", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeVirtual(virtualId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_virtual", { virtualId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addDevice(config: Device) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_device", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeDevice(deviceIp: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_device", { deviceIp }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setTargetFps(fps: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_target_fps", { fps }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getEffectSchema(effectId: string) : Promise<Result<EffectSetting[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_effect_schema", { effectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableEffects() : Promise<Result<EffectInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_effects") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDevices() : Promise<Result<Device[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getVirtuals() : Promise<Result<Virtual[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_virtuals") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioDevices() : Promise<Result<AudioDevicesInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setAudioDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_audio_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioAnalysis() : Promise<Result<AudioAnalysisData, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_analysis") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDspSettings() : Promise<Result<DspSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_dsp_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPlaybackState() : Promise<Result<PlaybackState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_playback_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async togglePause() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_pause") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSettings() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importSettings(data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_settings", { data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerReload() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_reload") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateDspSettings(settings: DspSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_dsp_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultEngineState() : Promise<Result<EngineState, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_engine_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async restartAudioCapture() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restart_audio_capture") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async calculateCenterFrequencies(numBands: number, minFreq: number, maxFreq: number, filterType: FilterbankType) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("calculate_center_frequencies", { numBands, minFreq, maxFreq, filterType }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async savePreset(effectId: string, presetName: string, settings: EffectConfig) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preset", { effectId, presetName, settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePreset(effectId: string, presetName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_preset", { effectId, presetName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadPresets(effectId: string) : Promise<Result<PresetCollection, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_presets", { effectId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveScene(scene: Scene) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_scene", { scene }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteScene(sceneId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_scene", { sceneId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activateScene(sceneId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_scene", { sceneId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getScenes() : Promise<Result<Scene[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_scenes") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type ActiveEffectsState = { active_scene_id: string | null; selected_effects: Partial<{ [key in string]: string }>; effect_settings: Partial<{ [key in string]: Partial<{ [key in string]: EffectConfig }> }>; active_effects: Partial<{ [key in string]: boolean }> }
export type AudioAnalysisData = { melbanks: number[] }
export type AudioDevice = { name: string }
export type AudioDevicesInfo = { devices: AudioDevice[]; default_device_name: string | null }
export type BaseEffectConfig = { mirror: boolean; flip: boolean; blur: number; background_color: string }
export type BladePlusParams = { log_base: number; multiplier: number; divisor: number }
export type BladePowerConfig = ({ mirror: boolean; flip: boolean; blur: number; background_color: string }) & { decay: number; multiplier: number; frequency_range: string; gradient: string }
export type Control = { type: "slider"; min: number; max: number; step: number } | { type: "checkbox" } | { type: "colorPicker" } | { type: "select"; options: string[] }
export type DefaultValue = string | number | boolean
export type Device = { ip_address: string; name: string; led_count: number }
export type DspSettings = { fft_size: number; num_bands: number; min_freq: number; max_freq: number; filterbank_type: FilterbankType; sample_rate: number | null; blade_plus_params: BladePlusParams | null; smoothing_factor: number; agc_attack: number; agc_decay: number; audio_delay_ms: number }
export type EffectConfig = { type: "blade_power"; config: BladePowerConfig } | { type: "fire"; config: FireConfig } | { type: "scan"; config: ScanConfig }
export type EffectInfo = { id: string; name: string }
export type EffectSetting = { id: string; name: string; description: string; control: Control; defaultValue: DefaultValue }
export type EngineState = { devices?: Partial<{ [key in string]: Device }>; virtuals?: Partial<{ [key in string]: Virtual }>; dsp_settings?: DspSettings; effect_presets?: Partial<{ [key in string]: Partial<{ [key in string]: EffectConfig }> }>; scenes?: Partial<{ [key in string]: Scene }> }
export type FilterbankType = "Balanced" | "Precision" | "Vocal" | "Blade" | { BladePlus: BladePlusParams }
export type FireConfig = ({ mirror: boolean; flip: boolean; blur: number; background_color: string }) & { cooling: number; sparking: number; gradient: string }
export type LedsInfo = { count: number }
export type MapInfo = { id: number }
export type MatrixCell = { device_id: string; pixel: number }
export type PlaybackState = { is_paused: boolean }
export type PresetCollection = { user: Partial<{ [key in string]: EffectConfig }>; built_in: Partial<{ [key in string]: EffectConfig }> }
export type ScanConfig = ({ mirror: boolean; flip: boolean; blur: number; background_color: string }) & { speed: number; width: number; gradient: string }
export type Scene = { id: string; name: string; virtual_effects: Partial<{ [key in string]: SceneEffect }> }
export type SceneEffect = { type: "preset"; data: ScenePreset } | { type: "custom"; data: EffectConfig }
export type ScenePreset = { effect_id: string; preset_name: string }
export type Virtual = { id: string; name: string; matrix_data: ((MatrixCell | null)[])[]; is_device?: string | null }
export type WledDevice = { ip_address: string; port: number; name: string; version: string; leds: LedsInfo; udp_port: number; architecture: string; maps: MapInfo[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
