name: Universal Cross-Platform Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # --- JOB 1: Build for Desktop ---
  build-desktop:
    name: Build Desktop - ${{ matrix.os }}
    if: startsWith(github.event.head_commit.message, 'Release')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22.x", cache: "yarn" }
      - uses: dtolnay/rust-toolchain@stable
      - run: yarn install --frozen-lockfile
      - name: Sync Version to tauri.conf.json
        shell: bash
        run: |
          node -e "
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
            const tauriConfPath = './src-tauri/tauri.conf.json';
            const tauriConf = JSON.parse(fs.readFileSync(tauriConfPath, 'utf8'));
            tauriConf.version = packageJson.version;
            fs.writeFileSync(tauriConfPath, JSON.stringify(tauriConf, null, 2));
          "
      - uses: tauri-apps/tauri-action@v0
        with:
          distPath: ./dist
      - uses: actions/upload-artifact@v4
        with:
          name: desktop-artifacts-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/dmg/*.dmg

  # --- JOB 2: Build for Android ---
  build-android:
    name: Build Android APK
    if: startsWith(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22.x", cache: "yarn" }
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add aarch64-linux-android
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with: { ndk-version: r25b }
      - run: yarn install --frozen-lockfile
      - name: Sync Version to tauri.conf.json
        shell: bash
        run: |
          node -e "
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
            const tauriConfPath = './src-tauri/tauri.conf.json';
            const tauriConf = JSON.parse(fs.readFileSync(tauriConfPath, 'utf8'));
            tauriConf.version = packageJson.version;
            fs.writeFileSync(tauriConfPath, JSON.stringify(tauriConf, null, 2));
          "
      - run: yarn tauri android init
        env:
          ANDROID_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - run: yarn tauri android build
        env:
          ANDROID_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - uses: actions/upload-artifact@v4
        with:
          name: android-artifact
          path: src-tauri/gen/android/app/build/outputs/apk/release/*.apk

  # --- JOB 3: Build for Raspberry Pi ---
  build-raspberry-pi:
    name: Build Raspberry Pi (ARM64)
    if: startsWith(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "22.x", cache: "yarn" }
      - uses: dtolnay/rust-toolchain@stable
      - name: Install cross-compilation tool
        uses: taiki-e/install-action@cross
      - name: Install ARM64 system dependencies
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev:arm64 libgtk-3-dev:arm64
      - run: yarn install --frozen-lockfile
      - name: Sync Version to tauri.conf.json
        shell: bash
        run: |
          node -e "
            const fs = require('fs');
            const packageJson = JSON.parse(fs.readFileSync('./package.json', 'utf8'));
            const tauriConfPath = './src-tauri/tauri.conf.json';
            const tauriConf = JSON.parse(fs.readFileSync(tauriConfPath, 'utf8'));
            tauriConf.version = packageJson.version;
            fs.writeFileSync(tauriConfPath, JSON.stringify(tauriConf, null, 2));
          "
      - run: yarn tauri build --target aarch64-unknown-linux-gnu --runner cross
      - uses: actions/upload-artifact@v4
        with:
          name: rpi-artifact
          path: src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/appimage/*.AppImage

  # --- FINAL JOB: Create the Release ---
  create-release:
    name: Create GitHub Release
    if: always() && startsWith(github.event.head_commit.message, 'Release')
    needs: [build-desktop, build-android, build-raspberry-pi]
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Version from package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Generate Changelog File
        id: generate_changelog_file
        run: |
          echo "## Changes in v${{ steps.get_version.outputs.VERSION }}" > changelog.md
          git log --pretty=format:"- %s ([%h](https://github.com/${{ github.repository }}/commit/%h))" $(git describe --tags --abbrev=0 HEAD^)..HEAD >> changelog.md
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          body_path: changelog.md
          files: |
            artifacts/**/*