name: Universal Cross-Platform Release

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  # --- JOB 1: Build for Desktop (Windows, macOS, Linux) ---
  build-desktop:
    name: Build Desktop - ${{ matrix.platform }}
    if: startsWith(github.event.head_commit.message, 'Release')
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false # <-- THE FIX: Don't cancel other jobs if one fails
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      # --- THE FIX: Install Linux GUI dependencies (only runs on ubuntu) ---
      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install frontend dependencies (Yarn)
        run: yarn install --frozen-lockfile

      - name: Install Tauri CLI
        run: yarn add -D @tauri-apps/cli

      - name: Build the application
        run: yarn tauri build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: desktop-artifacts-${{ matrix.platform }}
          path: |
            src-tauri/target/release/bundle/msi/*.msi
            src-tauri/target/release/bundle/appimage/*.AppImage
            src-tauri/target/release/bundle/dmg/*.dmg

  # --- JOB 2: Build for Android ---
  build-android:
    name: Build Android APK
    if: startsWith(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Add Android targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android
      - name: Setup Java (for Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      
      # --- THE DEFINITIVE FIX: Install the Android SDK/NDK ---
      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b # A stable, recommended version
          
      - name: Install frontend dependencies (Yarn)
        run: yarn install --frozen-lockfile
        
      - name: Install Tauri CLI
        run: yarn add -D @tauri-apps/cli
      
      - name: Initialize Tauri Android project
        # We must provide the ANDROID_HOME and NDK_HOME environment variables
        run: yarn tauri android init
        env:
          ANDROID_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Build Android APK
        run: yarn tauri android build
        env:
          ANDROID_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-artifact
          path: src-tauri/gen/android/app/build/outputs/apk/release/*.apk

  # --- JOB 3: Build for Raspberry Pi (ARM Linux) ---
  build-raspberry-pi:
    name: Build Raspberry Pi (ARM64)
    if: startsWith(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cross-compilation tools for ARM64 Linux
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: aarch64-unknown-linux-gnu
      
      # --- THE FIX: Install Linux GUI dependencies for cross-compilation ---
      - name: Install ARM64 Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev:arm64 libgtk-3-dev:arm64 libappindicator3-dev:arm64 librsvg2-dev:arm64

      - name: Install frontend dependencies (Yarn)
        run: yarn install --frozen-lockfile
      - name: Install Tauri CLI
        run: yarn add -D @tauri-apps/cli
      - name: Build the application for ARM64
        run: yarn tauri build --target aarch64-unknown-linux-gnu
      - name: Upload AppImage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpi-artifact
          path: src-tauri/target/aarch64-unknown-linux-gnu/release/bundle/appimage/*.AppImage

  # --- JOB 4: Build for iOS ---
  build-ios:
    name: Build iOS IPA
    # --- THE FIX: Only run this job if the secrets are present ---
    if: startsWith(github.event.head_commit.message, 'Release') && secrets.APPLE_CERTIFICATE_BASE64 != ''
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Add iOS targets
        run: rustup target add aarch64-apple-ios x86_64-apple-ios
      - name: Install frontend dependencies (Yarn)
        run: yarn install --frozen-lockfile
      - name: Install Tauri CLI
        run: yarn add -D @tauri-apps/cli
      - name: Install Apple certificate and provisioning profile
        # TODO: This is the complex part. You need to add your certs/profiles as secrets.
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.APPLE_CERTIFICATE_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
      - name: Build iOS App
        run: yarn tauri ios build
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-artifact
          path: src-tauri/gen/apple/build/release/*.ipa

  # --- FINAL JOB: Create the Release ---
  create-release:
    name: Create GitHub Release
    # This job now only needs the desktop and rpi builds to succeed
    needs: [build-desktop, build-raspberry-pi] # Add build-android and build-ios back when they are stable
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # ... (Release creation steps are unchanged)
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          # ...
          files: |
            artifacts/desktop-artifacts-windows-latest/*
            artifacts/desktop-artifacts-macos-latest/*
            artifacts/desktop-artifacts-ubuntu-22.04/*
            artifacts/rpi-artifact/*
            # artifacts/android-artifact/*
            # artifacts/ios-artifact/*